import { isObject } from 'lodash';

export const overrideValue = 'overridden';

export const defaultOverrideColumns = ['openingTimestamp', 'currentTimestamp', 'timestamp', 'reset', 'transactTime', 'time'];

/**
 * Override autogenerated timestamp columns with provided values.
 *
 * @param target
 * @param valueToOverride
 * @param targetColumns
 */
export function overrideTimestampColumns<T extends any>(
  target: T,
  valueToOverride: any = overrideValue,
  targetColumns: string[] = defaultOverrideColumns,
): T {
  if (target === null || target === undefined || typeof target === 'string' || typeof target === 'number' || typeof target === 'boolean') {
    return target;
  }

  if (Array.isArray(target)) {
    target.forEach((v: any) => overrideTimestampColumns(v, valueToOverride));
  } else {
    overrideProperties(target, valueToOverride, targetColumns);
  }

  return target;
}

function overrideProperties(object: { [key: string]: any }, valueToOverride: any, targetColumns: string[]): void {
  Object.keys(object).forEach((key) => {
    if (isObject(object[key])) {
      overrideProperties(object[key], valueToOverride, targetColumns);
    } else {
      if (targetColumns.includes(key)) {
        object[key] = valueToOverride;
      }
    }
  });
}
